CREATE TABLE AutoUsate (
IdAuto INT AUTO_INCREMENT PRIMARY KEY,
Marca VARCHAR(100) NOT NULL,
Modello VARCHAR(100) NOT NULL,
AnnoImmatricolazione YEAR NOT NULL,
KmPercorsi INT NOT NULL,
Prezzo DECIMAL(10, 2) NOT NULL,
Colore VARCHAR(50),
TipoCarburante VARCHAR(50),
)

